version: '3.8'
services:
  api:
    build: ./Backend
    ports:
      - "5000:80"
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_USER: tuUsuario
      POSTGRES_PASSWORD: tuPassword
      POSTGRES_DB: TareasDB
    ports:
      - "5432:5432"
  frontend:
    build: ./Frontend
    ports:
      - "3000:3000"
